version: '2'

services:
  loraserver:
    image: loraserver/loraserver:2
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  loraserver1:
    image: loraserver/loraserver:1
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
    - ./configuration/loraserver_1:/etc/loraserver

  lora_appserver:
    image: loraserver/lora-app-server:2
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8080:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  lora_appserver1:
    image: loraserver/lora-app-server:1
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8081:8080
    volumes:
      - ./configuration/lora-app-server_1:/etc/lora-app-server

  postgresql:
    image: postgres:9.6-alpine
    ports:
      - 5432
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    ports:
      - 6379
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883