FROM node:8

# set working directory
WORKDIR /app

RUN npm install -g mocha

# Copy Prisma client
COPY prisma/dev prisma/dev

# Copy project file
COPY package*.json ./

# install ALL node_modules, including 'devDependencies'
RUN npm ci

# copy all project
COPY . .

EXPOSE 3200

# Override the command, to run the test instead of the application
CMD ["mocha", "./test2.0/unit", "--recursive", "--reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js", "--timeout", "3000"]
