FROM ubuntu:latest

RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get -yq install sqlite3 && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./data ./data

RUN sqlite3 data/lpwanserver.sqlite3 < data/lpwanserver.2.2.generateSchema.sql \
&& sqlite3 data/lpwanserver.sqlite3 < data/lpwanserver.2.2.initializeData.sql

RUN ls ./data