version: '2'

services:
  api-test:
    image: lpwanserver/api-test
    environment:
      - NODE_ENV=e2e
      - PORT=3200
      - db_file=data/demo_data/demo.sqlite3
    depends_on:
      - loraserver1
      - lora_appserver1
    ports:
      - '3200:3200'

  postgresql:
    volumes:
      - ./configuration/postgresql/initdb-demo:/docker-entrypoint-initdb.d

  redis:
    volumes:
      - ../data/demo_data/redis:/data
