version: '2'

services:
  ui:
    image: lpwanserver/lpwanserver-web-client
    environment:
      - LPWANSERVER_PROTOCOL=http
      - LPWANSERVER_HOST=localhost
      - LPWANSERVER_PORT=3200
      - PORT=3000
    ports:
      - 3000:3000
    network_mode: host
