#!/usr/bin/env bash

# Remove old containers, volumes, and images
./bin/clean.js

# Start databases and prisma
./bin/manage-db start
./bin/manage-db deploy

# Start Lora Servers
docker-compose -f ./docker/dev/loraserver/docker-compose.yml up -d

# Run tests
docker-compose -f ./docker/test/api/docker-compose.yml up --build \
  --abort-on-container-exit \
  --exit-code-from api-test

TEST_EXIT_CODE=$?

#Stop LoRa Servers
docker-compose -f ./docker/dev/loraserver/docker-compose.yml down

# Stop databases and prisma
./bin/manage-db stop

# Exit script with the code from the test
exit $TEST_EXIT_CODE
