#!/usr/bin/env bash

sudo rm -r ./test/e2e/docker/data
sudo cp -r ./test/e2e/docker/data_baseline ./test/e2e/docker/data
#sudo mkdir ./test/e2e/docker/data/pg_commit_ts
#sudo mkdir ./test/e2e/docker/data/pg_dyn
#sudo mkdir ./test/e2e/docker/data/pg_commit_ts
#sudo mkdir ./test/e2e/docker/data/pg_commit_ts
#sudo mkdir ./test/e2e/docker/data/pg_commit_ts
#sudo mkdir ./test/e2e/docker/data/pg_commit_ts
#sudo mkdir ./test/e2e/docker/data/pg_commit_ts
#sudo mkdir ./test/e2e/docker/data/pg_commit_ts

# Run docker-compose with development configuration
docker-compose -f ./test/e2e/docker/docker-compose.yml up -d
npm run e2e
wait
docker-compose -f ./test/e2e/docker/docker-compose.yml down

